---
title: "Daily Exercise 19"
author: "Emily Wapman"
output: html_document
---

```{r, warning = FALSE, message = FALSE}
library(elevatr)
library(tidyverse)
library(sf)
library(raster)
library(rgdal)
library(osmdata)
library(dplyr)
library(leaflet)

bb = read_csv("~/github/geog176A-daily-exercises/data/uscities.csv") %>%
  st_as_sf(coords = c("lng", "lat"), crs = 4326) %>% 
  filter(city == "Goleta") %>% 
  st_transform(5070) %>% 
  st_buffer(5000) %>% 
  st_bbox() %>% 
  st_as_sfc() %>% 
  st_as_sf()

elev = elevatr::get_elev_raster(bb, z = 11) %>% crop(bb)
writeRaster(elev, filename = "~/github/geog176A-daily-exercises/data/goleta-elev.tif", overwrite = TRUE)

r = raster("~/github/geog176A-daily-exercises/data/goleta-elev.tif")

FUN2 = function(x) {ifelse(x <= 0 , NA, 1)}

mask = calc(r, FUN2)

land = mask * r
plot(land, col = viridis::viridis(256))

# Reclassify 
rcl = data.frame(min = seq(0, 500, 100), max = seq(100, 600, 100), lab = c(0:5))

raster_reclassify = reclassify(land, rcl, lowerTRUE = TRUE)

stack = stack(r, mask, land, raster_reclassify) %>%
  setNames(c("elevation", "land", "terrain", "topography"))

plot(stack, col = viridis::viridis(256))

```

# Day 19
```{r, warning = FALSE, message = FALSE}
bb2 = st_bbox(stack) %>%
  st_as_sfc() %>%
  st_transform(4326)
 
osm = osmdata::opq(bb2) %>%
  add_osm_feature(key = 'amenity', value = "restaurant") %>%
  osmdata_sf() 

restaurant = osm$osm_points 

elevation = raster::extract(r, restaurant)

restaurant_plot = restaurant %>%
  mutate(elevation = elevation) %>% 
  dplyr::select(osm_id, name, amenity, elevation) %>%
  dplyr::filter(!is.na(name)) 


leaflet() %>%
  addTiles() %>%
  addMarkers(data = restaurant_plot, popup = ~as.character(elevation), label = ~name)
  
  
  

```
